export const blogs = [
  {
    id: 1,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "PUBLISHED",
    publishDate: "1405/05/16",
    lastEditDate: "1405/05/18",
  },
  {
    id: 2,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "SAVED",
    publishDate: "",
    lastEditDate: "",
  },
  {
    id: 3,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "PUBLISHED",
    publishDate: "",
    lastEditDate: "1405/05/18",
  },
  {
    id: 4,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "SAVED",
    publishDate: "1405/05/16",
    lastEditDate: "",
  },
  {
    id: 5,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "SAVED",
    publishDate: "",
    lastEditDate: "",
  },
  {
    id: 6,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "PUBLISHED",
    publishDate: "1405/05/16",
    lastEditDate: "",
  },
  {
    id: 7,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "SAVED",
    publishDate: "",
    lastEditDate: "1405/05/18",
  },
  {
    id: 8,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "SAVED",
    publishDate: "1405/05/16",
    lastEditDate: "",
  },
  {
    id: 9,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "PUBLISHED",
    publishDate: "",
    lastEditDate: "",
  },
  {
    id: 10,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "SAVED",
    publishDate: "",
    lastEditDate: "",
  },
  {
    id: 11,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "PUBLISHED",
    publishDate: "1405/05/16",
    lastEditDate: "",
  },
  {
    id: 12,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "SAVED",
    publishDate: "",
    lastEditDate: "1405/05/18",
  },
  {
    id: 13,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "PUBLISHED",
    publishDate: "",
    lastEditDate: "",
  },
  {
    id: 14,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "SAVED",
    publishDate: "1405/05/16",
    lastEditDate: "",
  },
  {
    id: 15,
    articleName: "اسم مقاله نوشته میشه",
    createDate: "1405/05/15",
    status: "SAVED",
    publishDate: "",
    lastEditDate: "",
  },
];