export type TCountry = {
  fa: string;
  en: string;
  isoCode: string;
  code: string;
  phoneCode: string;
};
export const countries: TCountry[] = [
  {
    fa: "امارات متحده عربی",
    en: "United Arab Emirates",
    isoCode: "ar-AE",
    code: "AE",
    phoneCode: "+98",
  },
  {
    fa: "آلبانی", 
    en: "Albania",
    isoCode: "q-AL",
    phoneCode: "+355",
    code: "AL",
  },
  {
    fa: "ارمنستان",
    en: "Armenia",
    isoCode: "am-AM",
    phoneCode: "+374",
    code: "AM",
  },
  {
    fa: "آرژانتین",
    en: "Argentina",
    isoCode: "es-AR",
    phoneCode: "+54",
    code: "AR",
  },
  {
    fa: "اتریش",
    en: "Austria",
    isoCode: "de-AT",
    phoneCode: "+43",
    code: "AT",
  },
  {
    fa: "استرالیا",
    en: "Australia",
    isoCode: "en-AU",
    phoneCode: "+61",
    code: "AU",
  },
  {
    fa: "جمهوری آذربایجان",
    en: "Azerbaijan",
    isoCode: "az-AZ",
    phoneCode: "+994",
    code: "AZ",
  },
  {
    fa: "بوسنی و هرزگوین",
    en: "Bosnia and Herzegovina",
    isoCode: "bs-BA",
    phoneCode: "+387",
    code: "BA",
  },
  {
    fa: "بنگلادش",
    en: "Bangladesh",
    isoCode: "bn-BD",
    phoneCode: "+880",
    code: "BD",
  },
  {
    fa: "بلژیک",
    en: "Belgium",
    isoCode: "nl-BE",
    phoneCode: "+32",
    code: "BE",
  },
  {
    fa: "بحرین",
    en: "Bahrain",
    isoCode: "ar-BH",
    phoneCode: "+973",
    code: "BH",
  },
  {
    fa: "بولیوی",
    en: "Bolivia",
    isoCode: "es-BO",
    phoneCode: "+591",
    code: "BO",
  },
  {
    fa: "بلاروس",
    en: "Belarus",
    isoCode: "be-BY",
    phoneCode: "+375",
    code: "BY",
  },
  {
    fa: "کانادا",
    en: "Canada",
    isoCode: "ca-AD",
    phoneCode: "+1",
    code: "CA",
  },
  {
    fa: "سوئیس",
    en: "Switzerland",
    isoCode: "de-CH",
    code: "CH",
    phoneCode: "+41",
  },
  {
    fa: "شیلی",
    en: "Chile",
    isoCode: "es-CL",
    phoneCode: "+56",
    code: "CL",
  },
  {
    fa: "چین",
    en: "China",
    isoCode: "zh-CN",
    phoneCode: "+86",
    code: "CN",
  },
  {
    fa: "کلمبیا",
    en: "Colombia",
    isoCode: "es-CO",
    phoneCode: "+57",
    code: "CO",
  },
  {
    fa: "کاستاریکا",
    en: "Costa Rica",
    isoCode: "es-CR",
    phoneCode: "+506",
    code: "CR",
  },
  {
    fa: "جمهوری چک",
    en: "Czech Republic",
    isoCode: "cs-CZ",
    phoneCode: "+420",
    code: "CZ",
  },
  {
    fa: "دانمارک",
    en: "Denmark",
    isoCode: "da-DK",
    phoneCode: "+45",
    code: "DK",
  },
  {
    fa: "دومینیکا",
    en: "Dominican Republic",
    isoCode: "es-DO",
    phoneCode: "+1 809",
    code: "DO",
  },
  {
    fa: "الجزایر",
    en: "Algeria",
    isoCode: "ar-DZ",
    phoneCode: "+213",
    code: "DZ",
  },
  {
    fa: "اکوادور",
    en: "Ecuador",
    isoCode: "es-EC",
    phoneCode: "+593",
    code: "EC",
  },
  {
    fa: "استونی",
    en: "Estonia",
    isoCode: "et-EE",
    phoneCode: "+372",
    code: "EE",
  },
  {
    fa: "مصر",
    en: "Egypt",
    isoCode: "ar-EG",
    phoneCode: "+20",
    code: "EG",
  },
  {
    fa: "اسپانیا",
    en: "Spain",
    isoCode: "es-ES",
    code: "ES",
    phoneCode: "+34"
  },
  {
    fa: "فنلاند",
    en: "Finland",
    isoCode: "fi-FI",
    phoneCode: "+358",
    code: "FI",
  },
  {
    fa: "فیجی",
    en: "Fiji",
    isoCode: "fj-FJ",
    phoneCode: "+679",
    code: "FJ",
  },
  {
    fa: "جزایر فارو",
    en: "Faroe Islands",
    isoCode: "fo-FO",
    phoneCode: "+298",
    code: "FO",
  },
  {
    fa: "فرانسه",
    en: "France",
    isoCode: "fr-FR",
    phoneCode: "+33",
    code: "FR",
  },
  {
    fa: "گرجستان",
    en: "Germany",
    isoCode: "ka-GE",
    phoneCode: "+995",
    code: "GE",
  },
  {
    fa: "گویان فرانسه",
    en: "French Guiana",
    isoCode: "fr-GF",
    phoneCode: "+594",
    code: "GF",
  },
  {
    fa: "گرنزی",
    en: "Guernsey",
    isoCode: "en-GG",
    phoneCode: "+44",
    code: "GG",
  },
  {
    fa: "غنا",
    en: "Ghana",
    isoCode: "en-GH",
    phoneCode: "+233",
    code: "GH",
  },
  {
    fa: "گرینلند",
    en: "Greenland",
    isoCode: "kl-GL",
    phoneCode: "+299",
    code: "GL",
  },
  {
    fa: "جزیره گوادلوپ",
    en: "Guadeloupe",
    isoCode: "fr-GP",
    phoneCode: "+590",
    code: "GP",
  },
  {
    fa: "یونان",
    en: "Greece",
    isoCode: "el-GR",
    phoneCode: "+30",
    code: "GR",
  },
  {
    fa: "هنگ کنگ",
    en: "Hong Kong",
    isoCode: "en-HK",
    phoneCode: "+852",
    code: "HK",
  },
  {
    fa: "هندوراس",
    en: "Honduras",
    isoCode: "es-HN",
    phoneCode: "+504",
    code: "HN",
  },
  {
    fa: "مجارستان",
    en: "Hungary",
    isoCode: "hu-HU",
    phoneCode: "+36",
    code: "HU",
  },
  {
    fa: "اندونزی",
    en: "Indonesia",
    isoCode: "id-ID",
    phoneCode: "+62",
    code: "ID",
  },
  {
    fa: "جمهوری ایرلند",
    en: "Ireland",
    isoCode: "en-IE",
    phoneCode: "+353",
    code: "IE",
  },
  {
    fa: "فلسطین اشغالی (اسرائیل)",
    en: "Israel",
    isoCode: "he-IL",
    phoneCode: "+972",
    code: "IL",
  },
  {
    fa: "هند",
    en: "India",
    isoCode: "en-IN",
    phoneCode: "+91",
    code: "IN",
  },
  {
    fa: "عراق",
    en: "Iraq",
    isoCode: "ar-IQ",
    phoneCode: "+964",
    code: "IQ",
  },
  {
    fa: "ایران",
    en: "Iran",
    isoCode: "fa-IR",
    phoneCode: "+98",
    code: "IR",
  },
  {
    fa: "ایتالیا",
    en: "Italy",
    isoCode: "it-IT",
    phoneCode: "+39",
    code: "IT",
  },
  {
    fa: "اردن",
    en: "Jordan",
    isoCode: "ar-JO",
    phoneCode: "+962",
    code: "JO",
  },
  {
    fa: "ژاپن",
    en: "Japan",
    isoCode: "ja-JP",
    phoneCode: "+81",
    code: "JP",
  },
  {
    fa: "کنیا",
    en: "Kenya",
    isoCode: "en-KE",
    phoneCode: "+254",
    code: "KE",
  },
  {
    fa: "کره جنوبی",
    en: "South Korea",
    isoCode: "ko-KR",
    phoneCode: "+82",
    code: "KR",
  },
  {
    fa: "کویت",
    en: "Kuwait",
    isoCode: "ar-KW",
    phoneCode: "+965",
    code: "KW",
  },
  {
    fa: "قزاقستان",
    en: "Kazakhstan",
    isoCode: "kk-KZ",
    phoneCode: "+7",
    code: "KZ",
  },
  {
    fa: "لبنان",
    en: "Lebanon",
    isoCode: "ar-LB",
    phoneCode: "+961",
    code: "LB",
  },
  {
    fa: "سری لانکا",
    en: "Sri Lanka",
    isoCode: "i-LK",
    code: "LK",
    phoneCode: "+94"
  },
  {
    fa: "لیتوانی",
    en: "Lithuania",
    isoCode: "lt-LT",
    phoneCode: "+370",
    code: "LT",
  },
  {
    fa: "لوکزامبورگ",
    en: "Luxembourg",
    isoCode: "de-LU",
    phoneCode: "+352",
    code: "LU",
  },
  {
    fa: "لتونی",
    en: "Latvia",
    isoCode: "lv-LV",
    phoneCode: "+371",
    code: "LV",
  },
  {
    fa: "لیبی",
    en: "Libya",
    isoCode: "ar-LY",
    phoneCode: "+218",
    code: "LY",
  },
  {
    fa: "مراکش",
    en: "Morocco",
    isoCode: "ar-MA",
    phoneCode: "+212",
    code: "MA",
  },
  {
    fa: "ماکائو",
    en: "Macau",
    isoCode: "en-MO",
    phoneCode: "+853",
    code: "MO",
  },
  {
    fa: "مارتینیک",
    en: "Martinique",
    isoCode: "fr-MQ",
    phoneCode: "+596",
    code: "MQ",
  },
  {
    fa: "مالت",
    en: "Malta",
    isoCode: "en-MT",
    phoneCode: "+356",
    code: "MT",
  },
  {
    fa: "موریس",
    en: "Mauritius",
    isoCode: "en-MU",
    phoneCode: "+230",
    code: "MU",
  },
  {
    fa: "مکزیک",
    en: "Mexico",
    isoCode: "es-MX",
    phoneCode: "+52",
    code: "MX",
  },
  {
    fa: "مالزی",
    en: "Malaysia",
    isoCode: "ms-MY",
    phoneCode: "+60",
    code: "MY",
  },
  {
    fa: "موزامبیک",
    en: "Mozambique",
    isoCode: "mz-MZ",
    phoneCode: "+258",
    code: "MZ",
  },
  {
    fa: "نیجریه",
    en: "Nigeria",
    isoCode: "en-NG",
    phoneCode: "+234",
    code: "NG",
  },
  {
    fa: "هلند",
    en: "Netherlands",
    isoCode: "nl-NL",
    phoneCode: "+31",
    code: "NL",
  },
  {
    fa: "نروژ",
    en: "Norway",
    isoCode: "nn-NO",
    phoneCode: "+47",
    code: "NO",
  },
  {
    fa: "نپال",
    en: "Nepal",
    isoCode: "ne-NP",
    phoneCode: "+977",
    code: "NP",
  },
  {
    fa: "نیوزلند",
    en: "New Zealand",
    isoCode: "en-NZ",
    phoneCode: "+64",
    code: "NZ",
  },
  {
    fa: "عمان",
    en: "Oman",
    isoCode: "ar-OM",
    phoneCode: "+968",
    code: "OM",
  },
  {
    fa: "پاناما",
    en: "Panama",
    isoCode: "es-PA",
    phoneCode: "+507",
    code: "PA",
  },
  {
    fa: "پرو",
    en: "Peru",
    isoCode: "es-PE",
    phoneCode: "+51",
    code: "PE",
  },
  {
    fa: "فیلیپین",
    en: "Philippines",
    isoCode: "en-PH",
    phoneCode: "+63",
    code: "PH",
  },
  {
    fa: "پاکستان",
    en: "Pakistan",
    isoCode: "en-PK",
    phoneCode: "+92",
    code: "PK",
  },
  {
    fa: "لهستان",
    en: "Poland",
    isoCode: "pl-PL",
    phoneCode: "+48",
    code: "PL",
  },
  {
    fa: "پرتغال",
    en: "Portugal",
    isoCode: "pt-PT",
    phoneCode: "+351",
    code: "PT",
  },
  {
    fa: "پاراگوئه",
    en: "Paraguay",
    isoCode: "es-PY",
    phoneCode: "+595",
    code: "PY",
  },
  {
    fa: "ریونیون",
    en: "Réunion",
    isoCode: "fr-RE",
    phoneCode: "+262",
    code: "RE",
  },
  {
    fa: "رومانی",
    en: "Romania",
    isoCode: "ro-RO",
    phoneCode: "+40",
    code: "RO",
  },
  {
    fa: "صربستان",
    en: "Serbia",
    isoCode: "sr-RS",
    code: "RS",
    phoneCode: "+381"
  },
  {
    fa: "روسیه",
    en: "Russia",
    isoCode: "ru-RU",
    phoneCode: "+7",
    code: "RU",
  },
  {
    fa: "رواندا",
    en: "Rwanda",
    isoCode: "en-RW",
    phoneCode: "+250",
    code: "RW",
  },
  {
    fa: "عربستان سعودی",
    en: "Saudi Arabia",
    isoCode: "ar-SA",
    phoneCode: "+966",
    code: "SA",
  },
  {
    fa: "سوئد",
    en: "Sweden",
    isoCode: "v-SE",
    phoneCode: "+46",
    code: "SE",
  },
  {
    fa: "سنگاپور",
    en: "Singapore",
    isoCode: "en-SG",
    phoneCode: "+65",
    code: "SG",
  },
  {
    fa: "اسلوونی",
    en: "Slovenia",
    isoCode: "l-SI",
    phoneCode: "+386",
    code: "SI",
  },
  {
    fa: "اسلواکی",
    en: "Slovakia",
    isoCode: "k-SK",
    phoneCode: "+421",
    code: "SK",
  },
  {
    fa: "سیرالئون",
    en: "Sierra Leone",
    isoCode: "en-SL",
    phoneCode: "+232",
    code: "SL",
  },
  {
    fa: "سن مارینو",
    en: "San Marino",
    isoCode: "it-SM",
    phoneCode: "+378",
    code: "SM",
  },
  {
    fa: "سوریه",
    en: "Syria",
    isoCode: "ar-SY",
    phoneCode: "+963",
    code: "SY",
  },
  {
    fa: "تایلند",
    en: "Thailand",
    isoCode: "th-TH",
    phoneCode: "+66",
    code: "TH",
  },
  {
    fa: "تونس",
    en: "Tunisia",
    isoCode: "ar-TN",
    phoneCode: "+216",
    code: "TN",
  },
  {
    fa: "ترکیه",
    en: "Turkey",
    isoCode: "tr-TR",
    phoneCode: "+90",
    code: "TR",
  },
  {
    fa: "تایوان",
    en: "Taiwan",
    isoCode: "zh-TW",
    phoneCode: "+886",
    code: "TW",
  },
  {
    fa: "تانزانیا",
    en: "Tanzania",
    isoCode: "en-TZ",
    phoneCode: "+255",
    code: "TZ",
  },
  {
    fa: "اوکراین",
    en: "Ukraine",
    isoCode: "uk-UA",
    phoneCode: "+380",
    code: "UA",
  },
  {
    fa: "اوگاندا",
    en: "Uganda",
    isoCode: "en-UG",
    phoneCode: "+256",
    code: "UG",
  },
  {
    fa: "ایالات متحده",
    en: "United States",
    isoCode: "en-US",
    phoneCode: "+1",
    code: "US",
  },
  {
    fa: "اروگوئه",
    en: "Uruguay",
    isoCode: "es-UY",
    phoneCode: "+598",
    code: "UY",
  },
  {
    fa: "ازبکستان",
    en: "Uzbekistan",
    isoCode: "uz-UZ",
    phoneCode: "+998",
    code: "UZ",
  },
  {
    fa: "ونزوئلا",
    en: "Venezuela",
    isoCode: "es-VE",
    phoneCode: "+58",
    code: "VE",
  },
  {
    fa: "ویتنام",
    en: "Vietnam",
    isoCode: "vi-VN",
    phoneCode: "+84",
    code: "VN",
  },
  {
    fa: "آفریقای جنوبی",
    en: "South Africa",
    isoCode: "en-ZA",
    phoneCode: "+27",
    code: "ZA",
  },
  {
    fa: "زامبیا",
    en: "Zambia",
    isoCode: "en-ZM",
    phoneCode: "+260",
    code: "ZM",
  },
  {
    fa: "زیمبابوه",
    en: "Zimbabwe",
    isoCode: "en-ZW",
    phoneCode: "+263",
    code: "ZW",
  },
];
